### ISSUE TITLE
Support Composer - Package Manager

### ISSUE THREAD

**Issue by francoisneron** [paysafegroup/paysafe_sdk_php#7]
We should support different packaging platform so that merchants has a better way to handle and manage these external libraries.

https://packagist.org/

**Comment by PayLeaseBrian** [comment]
A little more color for this ticket...

This link https://packagist.org/about goes into a bit more detail regarding publishing to packagist. This project now has a composer.json, and that's important. But, it also should get tagged when there are updates (the link describes the tag name format). I see that the old optimalpayments/optimal-php-sdk package was tagged in Github and published to packagist, so I'm assuming the process isn't totally unfamiliar.

Also, last week there was a mass re-name of files to make the filename case match the class name case. This is a change w/ cascading effects. At present the composer.json references the custom autoloader function in `source/paysafe.php`. This autoloader expects all filenames to be all lowercase. For anyone working on a case-sensitive filesystem, this will be a problem. It's possible to modify the `composer.json` so that Composer will auto-generate a PSR-4 compliant autoloader (see: https://getcomposer.org/doc/04-schema.md#psr-4). However, this would require some updates to the existing documentation. I suppose it's a Paysafe business decision to decide whether to leverage the Composer autoloader and steer folks in the direction of Composer, or update the custom autoloader in `source/paysafe.php` to be case-sensitive/PSR-4 compliant.

**Comment by francoisneron** [comment]
Thank you for clarifying in-depth the requirement.

**Comment by asawarivaidya** [comment]
@PayLeaseBrian  Thank you for your clarification. We have fixed the autoloader issue. Please check the latest release for the same.

**Comment by PayLeaseBrian** [comment]
@asawarivaidya I see that new tag 1.0.3 was created today. However, the `composer.json` still has a `version` in it. This should be removed. If there is no version in composer.json, Packagist will base version on github tags.

**Comment by asawarivaidya** [comment]
@PayLeaseBrian Thanks again. We have fixed it right away.

**Comment by PayLeaseBrian** [comment]
Cool. On a related note, might consider setting up a service hook to keep Packagist up to date. See: https://packagist.org/about#how-to-update-packages
